Repository gluster/glusterfs, pull requests merged in 2020-11, with the labels that each got.

#1748 glusterd: resource leaks
  rpc/rpc-lib/src/rpc-clnt.c
  xlators/mgmt/glusterd/src/glusterd-svc-helper.c
Labels: release 7, release 8

#1821 glusterd: fix a bug in enabling nfs ganesha (#1813)
  xlators/mgmt/glusterd/src/glusterd-op-sm.c
Labels: release 8

#1828 posix: Use MALLOC instead of alloca to allocate memory for xattrs lis…
  xlators/storage/posix/src/posix-gfid-path.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 7

#1841 CLI: Added an error message in case of timeout
  cli/src/cli-rpc-ops.c
Labels: release 7

#1842 CLI: added an error message in case of timeout
  cli/src/cli-rpc-ops.c
Labels: release 8

#1847 test case ./tests/bugs/core/bug-1650403.t is getting timed out
  xlators/mgmt/glusterd/src/glusterd-ganesha.c
  xlators/mgmt/glusterd/src/glusterd-handler.c
  xlators/mgmt/glusterd/src/glusterd-handshake.c
  xlators/mgmt/glusterd/src/glusterd-mem-types.h
  xlators/mgmt/glusterd/src/glusterd-messages.h
  xlators/mgmt/glusterd/src/glusterd-op-sm.c
  xlators/mgmt/glusterd/src/glusterd-peer-utils.c
  xlators/mgmt/glusterd/src/glusterd-replace-brick.c
  xlators/mgmt/glusterd/src/glusterd-reset-brick.c
  xlators/mgmt/glusterd/src/glusterd-utils.c
  xlators/mgmt/glusterd/src/glusterd-utils.h
  xlators/mgmt/glusterd/src/glusterd.c
  xlators/mgmt/glusterd/src/glusterd.h
Labels: release 8

#1839 glusterd: resource leaks
  rpc/rpc-lib/src/rpc-clnt.c
  xlators/mgmt/glusterd/src/glusterd-svc-helper.c
Labels: release 7

#1845 posix: In the commit 2f044c4587c6db3cb82b6128f056ec2ea2bc1b98 the ret…
  xlators/storage/posix/src/posix-gfid-path.c
Labels: release 7

#1853 glusterd: Can't run rebalance due to long unix socket
  tests/bugs/glusterd/bug-1720556.t
  xlators/mgmt/glusterd/src/glusterd-rebalance.c
  xlators/mgmt/glusterd/src/glusterd.h
Labels: release 7

#1840 glusterd: resource leaks
  rpc/rpc-lib/src/rpc-clnt.c
  xlators/mgmt/glusterd/src/glusterd-svc-helper.c
Labels: release 8

#1827 posix: Use MALLOC instead of alloca to allocate memory for xattrs lis…
  xlators/storage/posix/src/posix-gfid-path.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 8

#1858 posix: In the commit 2f044c4587c6db3cb82b6128f056ec2ea2bc1b98 the ret
  xlators/storage/posix/src/posix-gfid-path.c
Labels: release 8
