Repository gluster/glusterfs, pull requests merged in 2020-10, with the labels that each got.

#1561 fixed AFR_READ_POLICY_GFID_PID_HASH policy bug
  xlators/cluster/afr/src/afr-common.c
Labels: release 8

#1588 geo-rep: Enable rsync verbose logging for debugging
  geo-replication/syncdaemon/resource.py
Labels: CB: geo-replication

#1562 fixed AFR_READ_POLICY_GFID_PID_HASH policy bug
  xlators/cluster/afr/src/afr-common.c
Labels: release 7
