Repository gluster/glusterfs, pull requests merged in 2021-12, with the labels that each got.

#2990 GF_ASSERT_AND_GOTO_WITH_ERROR improvements and fixes
  libglusterfs/src/glusterfs/common-utils.h
  xlators/features/bit-rot/src/stub/bit-rot-stub-helpers.c
  xlators/features/index/src/index.c
  xlators/protocol/client/src/client-common.c
  xlators/protocol/client/src/client-rpc-fops.c
  xlators/protocol/client/src/client-rpc-fops_v2.c
Labels: release 11

#2871 STACK_DESTROY/RESET: query frame->root->ctx->measure_latency once
  libglusterfs/src/glusterfs/stack.h
  xlators/performance/readdir-ahead/src/readdir-ahead.c
Labels: release 11

#3002 HA status is in FAILOVER when configuring NFS ganesha with pacemaker 2.1
  extras/ganesha/scripts/ganesha-ha.sh
Labels: Type:Bug, release 9, CB: ganesha-ha, release 10

#1763 inode: implement namespace at inode level
  api/src/glfs-resolve.c
  libglusterfs/src/glusterfs/glusterfs.h
  libglusterfs/src/glusterfs/inode.h
  libglusterfs/src/inode.c
  libglusterfs/src/libglusterfs.sym
  tests/basic/inode-namespace.t
  xlators/mount/fuse/src/fuse-bridge.c
  xlators/protocol/server/src/server-common.c
  xlators/protocol/server/src/server-common.h
  xlators/protocol/server/src/server-rpc-fops_v2.c
  xlators/storage/posix/src/posix-entry-ops.c
Labels: FA: Technical Debt, CB: libglusterfs, release 11

#2834 snapshots: plugin architecture
  cli/src/cli-rpc-ops.c
  xlators/mgmt/glusterd/src/Makefile.am
  xlators/mgmt/glusterd/src/glusterd-handshake.c
  xlators/mgmt/glusterd/src/glusterd-snapshot-utils.c
  xlators/mgmt/glusterd/src/glusterd-snapshot-utils.h
  xlators/mgmt/glusterd/src/glusterd-snapshot.c
  xlators/mgmt/glusterd/src/glusterd-store.c
  xlators/mgmt/glusterd/src/glusterd-store.h
  xlators/mgmt/glusterd/src/glusterd-utils.c
  xlators/mgmt/glusterd/src/glusterd-utils.h
  xlators/mgmt/glusterd/src/glusterd.h
  xlators/mgmt/glusterd/src/snapshot/glusterd-lvm-snapshot.c
Labels: release 10

#3045 fuse-bridge.c: fix clang-scan warning on uninitialized use
  xlators/mount/fuse/src/fuse-bridge.c
Labels: release 11

#3032 multiple files: remove unused this from gf_link_inode_from_dirent()
  api/src/glfs-fops.c
  libglusterfs/src/gf-dirent.c
  libglusterfs/src/glusterfs/gf-dirent.h
  libglusterfs/src/syncop-utils.c
  xlators/mount/fuse/src/fuse-bridge.c
  xlators/nfs/server/src/nfs3.c
  xlators/protocol/server/src/server-rpc-fops.c
  xlators/protocol/server/src/server-rpc-fops_v2.c
Labels: release 11

#3042 socket.c: comment properly what the SSL version is
  rpc/rpc-transport/socket/src/socket.c
  xlators/features/cloudsync/src/cloudsync-plugins/src/cloudsyncs3/src/libcloudsyncs3.c
Labels: release 11

#2931 glusterd/brick: Do not connect into the backup volfile server
  glusterfsd/src/glusterfsd-mgmt.c
Labels: release 9

#3000 configure: Enable ltcmalloc_minimal instead of ltcmalloc
  configure.ac
Labels: release 10

#3040 posix_disk_space_check: save multiplication if using percentage
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-diskusage.c
  xlators/cluster/dht/src/dht-rebalance.c
  xlators/cluster/dht/src/dht-shared.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix.h
Labels: release 11

#3082 dht-common: combine time updates for pre and post stats
  xlators/cluster/dht/src/dht-common.c
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-helper.c
Labels: release 11

#3046 posix_check_internal_writes() - remove dict actions from lock
  xlators/storage/posix/src/posix-handle.h
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 11
