Repository gluster/glusterfs, pull requests merged in 2021-11, with the labels that each got.

#2918 SELinux: persist ganesha_use_fusefs over an upgrade
  glusterfs.spec.in
Labels: release 9, release 10

#2917 glusterfs.spec.in: issues with libtcmalloc
  glusterfs.spec.in
Labels: release 10

#2897 options.h: remove redundant calls to 'THIS'
  libglusterfs/src/glusterfs/options.h
Labels: release 11

#2876 caa_unlikely/likely for some common validations
  libglusterfs/src/glusterfs/common-utils.h
  libglusterfs/src/glusterfs/mem-pool.h
  libglusterfs/src/mem-pool.c
Labels: release 11

#2869 Dict.: remove prev
  libglusterfs/src/dict.c
  libglusterfs/src/glusterfs/dict.h
Labels: release 11

#2874 Multiple files: use lkowner_copy() instead of direct assignment
  libglusterfs/src/default-args.c
  libglusterfs/src/fd-lk.c
  libglusterfs/src/glusterfs/fd-lk.h
  libglusterfs/src/glusterfs/glusterfs.h
  libglusterfs/src/glusterfs/lkowner.h
  libglusterfs/src/glusterfs/stack.h
  libglusterfs/src/glusterfs/syncop.h
  libglusterfs/src/syncop.c
  xlators/cluster/afr/src/afr-common.c
  xlators/cluster/afr/src/afr-lk-common.c
  xlators/cluster/afr/src/afr-transaction.c
  xlators/cluster/afr/src/afr.h
  xlators/cluster/dht/src/dht-inode-read.c
  xlators/cluster/dht/src/dht-lock.c
  xlators/cluster/ec/src/ec-locks.c
  xlators/features/locks/src/common.c
  xlators/features/locks/src/entrylk.c
  xlators/features/locks/src/inodelk.c
  xlators/features/locks/src/locks.h
  xlators/features/locks/src/posix.c
  xlators/features/quota/src/quotad-helpers.c
  xlators/nfs/server/src/nfs-fops.c
  xlators/performance/write-behind/src/write-behind.c
  xlators/protocol/client/src/client-helpers.c
  xlators/protocol/client/src/client-lk.c
  xlators/protocol/client/src/client-rpc-fops.c
  xlators/protocol/client/src/client-rpc-fops_v2.c
  xlators/protocol/server/src/server-helpers.c
Labels: release 11

#2875 lkowner.h: improve lkowner_unparse() efficiency
  libglusterfs/src/common-utils.c
  libglusterfs/src/glusterfs/common-utils.h
  libglusterfs/src/glusterfs/lkowner.h
Labels: release 11

#2965 multiple files: remove the stub pool
  api/src/glfs.c
  cli/src/cli.c
  glusterfsd/src/glusterfsd.c
  libglusterfs/src/glusterfs/glusterfs.h
  xlators/features/changelog/lib/src/gf-changelog.c
  xlators/protocol/server/src/server.c
Labels: FA: Technical Debt, release 11
