Repository gluster/glusterfs, pull requests merged in 2022-09, with the labels that each got.

#3765 Multiple files: clean glusterd_is_local_brick()
  xlators/mgmt/glusterd/src/glusterd-bitrot.c
  xlators/mgmt/glusterd/src/glusterd-brick-ops.c
  xlators/mgmt/glusterd/src/glusterd-server-quorum.c
  xlators/mgmt/glusterd/src/glusterd-snapshot.c
  xlators/mgmt/glusterd/src/glusterd-utils.c
  xlators/mgmt/glusterd/src/glusterd-utils.h
  xlators/mgmt/glusterd/src/glusterd-volgen.c
Labels: release 11

#3769 test: test case bug-1702299.t is failing on centos-8 (#2864)
  tests/bugs/bug-1702299.t
Labels: release 9

#3707 gfapi: Add support for 'AT_EMPTY_PATH' flag
  api/src/glfs-fops.c
  api/src/glfs-internal.h
  api/src/glfs-resolve.c
  libglusterfs/src/glusterfs/common-utils.h
  tests/basic/gfapi/gfapi-o-path.c
Labels: release 11

#3784 tests: Increase timeout for sparse_file_rebalance.t test case (#3779)
  tests/basic/distribute/sparse_file_rebalance.t
Labels: release 9

#3757 posix: Handle `glusterfs.get_real_filename` virtual xattr in `fgetxattr()` (#3726)
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 10

#3755 Allow opening directories using `glfs_open()` / `glfs_h_open()` from libgfapi (#3307, #3650)
  api/src/glfs-fops.c
  api/src/glfs-handleops.c
  api/src/glfs-internal.h
  api/src/glfs.c
Labels: release 10

#3763 Additional #ifdef if gNFS is not compiled
  libglusterfs/src/inode.c
  libglusterfs/src/xlator.c
  rpc/rpc-lib/src/rpc-drc.c
  rpc/rpc-lib/src/rpc-transport.c
  rpc/rpc-lib/src/rpc-transport.h
  rpc/rpc-lib/src/rpcsvc-auth.c
  rpc/rpc-lib/src/rpcsvc.c
  rpc/rpc-lib/src/rpcsvc.h
  rpc/xdr/src/xdr-generic.c
  xlators/mgmt/glusterd/src/glusterd-volume-set.c
Labels: release 11

#3756 Allow opening snapshot directory(entrypoint) via `glfs_open()`/`glfs_h_open()` (#3667)
  xlators/features/snapview-server/src/snapview-server.c
Labels: release 10

#3759 Allow opening snapshot directory(entrypoint) via `glfs_open()`/`glfs_h_open()` (#3667)
  xlators/features/snapview-server/src/snapview-server.c
Labels: release 9

#3788 dht-hashfn.c: remove strcpy() from DHT calculation
  xlators/cluster/dht/src/dht-hashfn.c
Labels: release 11

#3749 inode.c: minor code changes
  libglusterfs/src/glusterfs/inode.h
  libglusterfs/src/inode.c
  libglusterfs/src/libglusterfs.sym
Labels: release 11

#3747 gf_svc_releasedir() was not freeing memory
  xlators/features/snapview-client/src/snapview-client.c
Labels: release 11

#3789 posix-pstat() - delay gfid copying to after lstat() succeeded
  xlators/storage/posix/src/posix-helpers.c
Labels: release 11

#3758 Allow opening directories using `glfs_open()` / `glfs_h_open()` from libgfapi (#3307, #3650)
  api/src/glfs-fops.c
  api/src/glfs-handleops.c
  api/src/glfs-internal.h
  api/src/glfs.c
Labels: release 9

#3809 posix_disk_space_check, dht_disk_usage: save multiplcation if using p…
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-diskusage.c
  xlators/cluster/dht/src/dht-rebalance.c
  xlators/cluster/dht/src/dht-shared.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix.h
Labels: release 9

#3810 dht: Implement seek fop at dht level
  tests/basic/distribute/dht_seek_test.t
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-helper.c
  xlators/cluster/dht/src/dht-inode-read.c
  xlators/cluster/dht/src/dht.c
Labels: release 9

#3811 dht: Implement seek fop at dht level
  tests/basic/distribute/dht_seek_test.t
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-helper.c
  xlators/cluster/dht/src/dht-inode-read.c
  xlators/cluster/dht/src/dht.c
Labels: release 10

#3807 lock/clear: Perform stack unwind outside of the inode lock (#3775)
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/common.h
Labels: release 9

#3760 posix: Handle `glusterfs.get_real_filename` virtual xattr in `fgetxattr()` (#3726)
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 9

#3736 Fix qemu-img crash on a distributed volume (#3720)
  xlators/protocol/client/src/client-rpc-fops_v2.c
Labels: release 10

#3808 lock/clear: Perform stack unwind outside of the inode lock (#3775)
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/common.h
Labels: release 10

#3819 Fix compilation warning with gNFS enabled
  rpc/xdr/src/xdr-generic.c
Labels: EasyFix, release 11

#3713 bit-rot: remove unused iatt variable
  xlators/features/bit-rot/src/bitd/bit-rot-scrub.c
  xlators/features/bit-rot/src/bitd/bit-rot.c
  xlators/features/bit-rot/src/bitd/bit-rot.h
Labels: EasyFix, release 11

#3723 mem-pool.c: remove redundant calls to 'THIS'
  libglusterfs/src/mem-pool.c
Labels: release 11

#3764 Small dictionary code improvements
  libglusterfs/src/dict.c
  libglusterfs/src/glusterfs/dict.h
  libglusterfs/src/libglusterfs.sym
  xlators/mgmt/glusterd/src/glusterd-utils.c
Labels: release 11

#3802 cdc xlator improvements
  tests/basic/cdc.t
  xlators/features/compress/src/cdc-helper.c
  xlators/features/compress/src/cdc.c
  xlators/features/compress/src/cdc.h
Labels: release 11

#3773 mem-pool.c: improve invalidate() function
  libglusterfs/src/glusterfs/mem-pool.h
  libglusterfs/src/mem-pool.c
Labels: release 11

#3451 refactor logging.c - remove 'THIS' where possible, use 'log instead of 'ctx' where possible
  glusterfsd/src/glusterfsd.c
  libglusterfs/src/common-utils.c
  libglusterfs/src/glusterfs/common-utils.h
  libglusterfs/src/glusterfs/logging.h
  libglusterfs/src/logging.c
  libglusterfs/src/statedump.c
  libglusterfs/src/xlator.c
  tests/basic/logchecks.c
  xlators/debug/io-stats/src/io-stats.c
Labels: release 11

#3818 posix_disk_space_check, dht_disk_usage: save multiplcation if using p…
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-diskusage.c
  xlators/cluster/dht/src/dht-rebalance.c
  xlators/cluster/dht/src/dht-shared.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix.h
Labels: release 10

#3697 tests: do not zero first sectors of LV, do not discard on mkfs.xfs
  tests/snapshot.rc
Labels: release 11

#3777 ec-common, helpers: minor cleanups
  xlators/cluster/ec/src/ec-common.c
  xlators/cluster/ec/src/ec-common.h
  xlators/cluster/ec/src/ec-helpers.c
  xlators/cluster/ec/src/ec-helpers.h
Labels: DO-NOT-MERGE

#3709 afr-no-fsync.t: disable cluster.lookup-optimize and skip initial FSYN…
  tests/basic/afr/afr-no-fsync.t
Labels: release 11

#3730 fd_ctx_get() and fd_ctx_del() should just return the value
  api/src/glfs-fops.c
  libglusterfs/src/fd.c
  libglusterfs/src/glusterfs/fd.h
  libglusterfs/src/libglusterfs.sym
  xlators/cluster/afr/src/afr-common.c
  xlators/cluster/afr/src/afr-lk-common.c
  xlators/cluster/afr/src/afr.h
  xlators/cluster/dht/src/dht-helper.c
  xlators/cluster/ec/src/ec-helpers.c
  xlators/cluster/ec/src/ec.c
  xlators/debug/io-stats/src/io-stats.c
  xlators/features/bit-rot/src/stub/bit-rot-stub-helpers.c
  xlators/features/bit-rot/src/stub/bit-rot-stub.c
  xlators/features/changelog/src/changelog.c
  xlators/features/index/src/index.c
  xlators/features/leases/src/leases-internal.c
  xlators/features/leases/src/leases.c
  xlators/features/locks/src/posix.c
  xlators/features/read-only/src/worm.c
  xlators/features/shard/src/shard.c
  xlators/features/snapview-client/src/snapview-client.c
  xlators/features/snapview-server/src/snapview-server-helpers.c
  xlators/features/snapview-server/src/snapview-server.c
  xlators/meta/src/meta-helpers.c
  xlators/mount/fuse/src/fuse-bridge.c
  xlators/mount/fuse/src/fuse-resolve.c
  xlators/nfs/server/src/nfs3.c
  xlators/performance/io-cache/src/io-cache.c
  xlators/performance/open-behind/src/open-behind.c
  xlators/performance/read-ahead/src/page.c
  xlators/performance/read-ahead/src/read-ahead.c
  xlators/performance/readdir-ahead/src/readdir-ahead.c
  xlators/performance/write-behind/src/write-behind.c
  xlators/protocol/client/src/client-helpers.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 11

#3805 posix: posix xlator does not respects storage.reserve value (#3637)
  tests/bugs/posix/bug-1651445.t
  tests/bugs/replicate/bug-1586020-mark-dirty-for-entry-txn-on-quorum-failure.t
  tests/bugs/shard/issue-2038.t
  xlators/protocol/server/src/server-rpc-fops_v2.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-entry-ops.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix.h
Labels: release 10

#3381 Multiple files: reduce padding in structures
  glusterfsd/src/glusterfsd.c
  libglusterfs/src/glusterfs/circ-buff.h
  libglusterfs/src/glusterfs/client_t.h
  libglusterfs/src/glusterfs/glusterfs.h
  libglusterfs/src/glusterfs/inode.h
  libglusterfs/src/glusterfs/options.h
  libglusterfs/src/glusterfs/stack.h
  libglusterfs/src/glusterfs/syncop.h
  rpc/rpc-lib/src/rpc-clnt.h
  rpc/rpc-lib/src/rpcsvc.h
  xlators/cluster/afr/src/afr.h
  xlators/cluster/dht/src/dht-common.h
  xlators/debug/io-stats/src/io-stats.c
  xlators/features/shard/src/shard.h
  xlators/lib/src/libxlator.h
  xlators/mgmt/glusterd/src/glusterd-sm.h
  xlators/mgmt/glusterd/src/glusterd.h
  xlators/performance/md-cache/src/md-cache.c
  xlators/performance/read-ahead/src/read-ahead.h
  xlators/performance/write-behind/src/write-behind.c
  xlators/protocol/client/src/client.h
  xlators/protocol/server/src/server.h
  xlators/storage/posix/src/posix-aio.c
  xlators/storage/posix/src/posix.h
Labels: release 11

#3421 marker.c: lookup - skip dict ref/unref if marker version is not valid
  xlators/features/marker/src/marker.c
Labels: release 11

#3712 syncop functions: no need to copy iatt structs if you are not going t…
  api/src/glfs-fops.c
  api/src/glfs-handleops.c
  heal/src/glfs-heal.c
  xlators/cluster/dht/src/dht-rebalance.c
  xlators/features/bit-rot/src/bitd/bit-rot-scrub.c
  xlators/features/bit-rot/src/bitd/bit-rot.c
  xlators/features/marker/src/marker-quota.c
  xlators/mount/fuse/src/fuse-bridge.c
  xlators/protocol/server/src/server-handshake.c
Labels: release 11
