Repository gluster/glusterfs, pull requests merged in 2022-03, with the labels that each got.

#3044 store, glusterd-store: improve store read iteration code
  libglusterfs/src/glusterfs/store.h
  libglusterfs/src/store.c
  xlators/mgmt/glusterd/src/glusterd-store.c
Labels: release 11

#2872 server-helpers.c: streamline get_frame_from_request() function
  xlators/protocol/server/src/server-helpers.c
  xlators/protocol/server/src/server.h
Labels: release 11

#2966 cli.c: do not use iobuf pool
  cli/src/cli.c
  libglusterfs/src/glusterfs/iobuf.h
  libglusterfs/src/iobuf.c
  libglusterfs/src/libglusterfs.sym
Labels: release 11

#3271 configure: Fix incorrect directory check
  configure.ac
  glusterfs.spec.in
Labels: release 10

#3204 Glustereventsd Default port change (#2091)
  events/src/eventsconfig.json
  extras/firewalld/glusterfs.xml
  libglusterfs/src/events.c
Labels: release 9

#3146 rpc clnt - cleanups
  rpc/rpc-lib/src/libgfrpc.sym
  rpc/rpc-lib/src/rpc-clnt.c
  rpc/rpc-lib/src/rpc-clnt.h
Labels: release 11

#3297 Locks: Optimize the interrupt flow of POSIX locks
  libglusterfs/src/glusterfs/glusterfs.h
  xlators/cluster/afr/src/afr-inode-read.c
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/clear.h
  xlators/features/locks/src/posix.c
  xlators/mount/fuse/src/fuse-bridge.c
Labels: release 9

#3008 multiple files: improve gf_dirent_for_name() functionality
  libglusterfs/src/default-args.c
  libglusterfs/src/gf-dirent.c
  libglusterfs/src/glusterfs/gf-dirent.h
  libglusterfs/src/libglusterfs.sym
  xlators/cluster/dht/src/dht-common.c
  xlators/cluster/dht/src/dht-rebalance.c
  xlators/features/index/src/index.c
  xlators/features/upcall/src/upcall-internal.c
  xlators/meta/src/meta-defaults.c
  xlators/mount/fuse/src/fuse-bridge.c
  xlators/mount/fuse/src/fuse-helpers.c
  xlators/performance/readdir-ahead/src/readdir-ahead.c
  xlators/protocol/client/src/client-helpers.c
  xlators/storage/posix/src/posix-handle.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 11

#3285 event-epoll.c: do not CALLOC a whole table
  libglusterfs/src/event-epoll.c
  libglusterfs/src/glusterfs/gf-event.h
Labels: release 11

#3332 Garbage value fix
  xlators/features/locks/src/reservelk.c
Labels: release 9

#3333 Garbage value fix
  xlators/features/locks/src/reservelk.c
Labels: release 10

#3350 server:Optimize server_process_event_upcall code path
  xlators/protocol/server/src/server.c
Labels: release 10

#3341 rpc: avoid restarting the bail out timer after initiating shut down
  rpc/rpc-lib/src/rpc-clnt.c
Labels: release 9

#3352 dht: Synchronize layout_(ref|unref) during layout_(get|set) in dht code
  xlators/cluster/dht/src/dht-common.c
  xlators/cluster/dht/src/dht-common.h
  xlators/cluster/dht/src/dht-diskusage.c
  xlators/cluster/dht/src/dht-helper.c
  xlators/cluster/dht/src/dht-layout.c
  xlators/cluster/dht/src/dht-selfheal.c
  xlators/cluster/dht/src/dht-shared.c
Labels: release 10

#3351 server:Optimize server_process_event_upcall code path
  xlators/protocol/server/src/server.c
Labels: release 9

#3349 rpc: avoid restarting the bail out timer after initiating shut down
  rpc/rpc-lib/src/rpc-clnt.c
Labels: release 10

#3293 dht-helper.c: simplify dht_local_init()
  xlators/cluster/dht/src/dht-helper.c
Labels: release 11

#3360 meta.c/.h: meta_lookup() and other small improvements
  xlators/meta/src/meta-defaults.c
  xlators/meta/src/meta-helpers.c
  xlators/meta/src/meta.c
  xlators/meta/src/meta.h
Labels: release 11

#3361 loc_gfid and loc_pargfid should not unconditionally clear the gfid
  libglusterfs/src/xlator.c
  xlators/mount/fuse/src/fuse-helpers.c
Labels: release 11

#3318 Upcall minor improvements
  xlators/features/upcall/src/upcall-internal.c
  xlators/features/upcall/src/upcall.c
  xlators/features/upcall/src/upcall.h
Labels: release 11

#1750 Simple quota: based on namespace
  configure.ac
  extras/hook-scripts/set/post/S61simple-quota.sh
  extras/quota/simple-quota.sh
  glusterfs.spec.in
  libglusterfs/src/glusterfs/common-utils.h
  libglusterfs/src/glusterfs/globals.h
  libglusterfs/src/glusterfs/glusterfs.h
  libglusterfs/src/inode.c
  tests/basic/inode-namespace.t
  tests/features/simple-quota-dht.t
  tests/features/simple-quota.t
  xlators/cluster/dht/src/dht-common.c
  xlators/cluster/dht/src/dht-common.h
  xlators/features/Makefile.am
  xlators/features/simple-quota/Makefile.am
  xlators/features/simple-quota/README.md
  xlators/features/simple-quota/src/Makefile.am
  xlators/features/simple-quota/src/simple-quota.c
  xlators/features/simple-quota/src/simple-quota.h
  xlators/mgmt/glusterd/src/glusterd-volgen.c
  xlators/mgmt/glusterd/src/glusterd-volume-set.c
  xlators/storage/posix/src/posix-entry-ops.c
Labels: release 11
