Repository gluster/glusterfs, pull requests merged in 2022-05, with the labels that each got.

#3488 socket: fix user-after-free on name resolution error
  rpc/rpc-transport/socket/src/socket.c
Labels: release 10

#3320 afr-self-heal: remove unused afr_selfheal_tryinodelk() function
  libglusterfs/src/gf-dirent.c
  xlators/cluster/afr/src/afr-self-heal-common.c
  xlators/cluster/afr/src/afr-self-heal.h
Labels: release 11

#3319 afr: check for parent gfid before calling afr_is_private_directory()
  xlators/cluster/afr/src/afr-common.c
  xlators/cluster/afr/src/afr-dir-read.c
  xlators/cluster/afr/src/afr-self-heal-entry.c
  xlators/cluster/afr/src/afr.h
Labels: release 11

#3324 afr-inode-write.c: remove one lock/unlock cycle
  xlators/cluster/afr/src/afr-inode-write.c
Labels: release 11

#3489 socket: fix user-after-free on name resolution error
  rpc/rpc-transport/socket/src/socket.c
Labels: release 9

#3460 posix-handle: remove posix_handle_unset() and call posix_handle_unset…
  xlators/storage/posix/src/posix-entry-ops.c
  xlators/storage/posix/src/posix-handle.c
  xlators/storage/posix/src/posix-handle.h
  xlators/storage/posix/src/posix-helpers.c
Labels: release 11

#3491 minor improvements to server-resolve
  xlators/protocol/server/src/server-resolve.c
  xlators/protocol/server/src/server.h
Labels: release 11

#3310 Locks: Optimize the interrupt flow of POSIX locks
  libglusterfs/src/glusterfs/glusterfs.h
  xlators/cluster/afr/src/afr-inode-read.c
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/clear.h
  xlators/features/locks/src/posix.c
  xlators/mount/fuse/src/fuse-bridge.c
Labels: release 10
