Repository gluster/glusterfs, pull requests merged in 2022-04, with the labels that each got.

#3383 dict.c/h: remove hash code
  libglusterfs/src/dict.c
  libglusterfs/src/glusterfs/dict.h
Labels: release 11

#3327 afr: __afr_inode_ctx_get() should return a pointer
  xlators/cluster/afr/src/afr-common.c
  xlators/cluster/afr/src/afr-transaction.c
  xlators/cluster/afr/src/afr.h
Labels: release 11

#3399 glusterd: After node reboot not able to start all bricks successfully
  xlators/mgmt/glusterd/src/glusterd-utils.c
Labels: release 9

#3398 glusterd: After node reboot not able to start all bricks successfully
  xlators/mgmt/glusterd/src/glusterd-utils.c
Labels: release 10

#3342 [RFE] logging: new way of defining and using log messages
  doc/developer-guide/logging-guidelines.md
  extras/create_new_xlator/new-xlator.c.tmpl
  libglusterfs/src/glusterfs/glfs-message-id.h
  libglusterfs/src/glusterfs/logging.h
  libglusterfs/src/glusterfs/template-component-messages.h
  xlators/features/quiesce/src/quiesce-messages.h
  xlators/features/quiesce/src/quiesce.c
Labels: Type:Enhancement

#3423 xlator_t: remove inconsistent alignment attribute
  libglusterfs/src/glusterfs/xlator.h
Labels: release 10

#3463 cli.c: cli_local_get() did not check for GF_CALLOC() success
  cli/src/cli.c
Labels: release 11
