Repository gluster/glusterfs, pull requests merged in 2022-02, with the labels that each got.

#3199 dht: Resolve double free in function dht_common_mark_mdsxattr_cbk
  xlators/cluster/dht/src/dht-common.c
Labels: release 10

#3198 dht: Resolve double free in function dht_common_mark_mdsxattr_cbk
  xlators/cluster/dht/src/dht-common.c
Labels: release 9

#3041 Events: make structures more memory friendly
  cli/src/cli-rl.c
  libglusterfs/src/event-epoll.c
  libglusterfs/src/event-poll.c
  libglusterfs/src/event.c
  libglusterfs/src/glusterfs/gf-event.h
  rpc/rpc-lib/src/rpc-transport.h
  rpc/rpc-transport/socket/src/socket.c
Labels: release 11

#3039 multiple files: skip fetching ctime if not needed.
  xlators/storage/posix/src/posix-aio.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-entry-ops.c
  xlators/storage/posix/src/posix-handle.c
  xlators/storage/posix/src/posix-handle.h
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix-inode-handle.h
  xlators/storage/posix/src/posix-io-uring.c
  xlators/storage/posix/src/posix-metadata.c
  xlators/storage/posix/src/posix.h
Labels: release 11

#3014 Multiple files: reduce the work needed to format the time in a log line
  cli/src/cli-rpc-ops.c
  cli/src/cli-xml-output.c
  glusterfsd/src/glusterfsd.c
  libglusterfs/src/common-utils.c
  libglusterfs/src/glusterfs/common-utils.h
  libglusterfs/src/libglusterfs.sym
  libglusterfs/src/logging.c
  libglusterfs/src/stack.c
  libglusterfs/src/statedump.c
  rpc/rpc-lib/src/rpc-clnt.c
  xlators/debug/io-stats/src/io-stats.c
  xlators/features/bit-rot/src/bitd/bit-rot-scrub.c
  xlators/features/locks/src/posix.c
  xlators/mgmt/glusterd/src/glusterd-handler.c
  xlators/mgmt/glusterd/src/glusterd-snapshot.c
  xlators/mgmt/glusterd/src/glusterd-utils.c
  xlators/performance/io-cache/src/io-cache.c
  xlators/performance/quick-read/src/quick-read.c
  xlators/storage/posix/src/posix-helpers.c
Labels: release 11

#3013 posix-*: reduce the impact of CloudSync feature on some IO paths
  xlators/storage/posix/src/posix-entry-ops.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
  xlators/storage/posix/src/posix.h
Labels: release 11

#3007 common-utils: replace gf_strdup() with gf_strndup() where applicable.
  libglusterfs/src/common-utils.c
  libglusterfs/src/glusterfs/common-utils.h
Labels: release 11

#2980 call-stub.c: do not unconditionally set errno
  libglusterfs/src/call-stub.c
Labels: release 11

#3009 client-*: adjust removal of 'this' from client functions
  xlators/protocol/client/src/client-common.c
  xlators/protocol/client/src/client-common.h
  xlators/protocol/client/src/client-helpers.c
  xlators/protocol/client/src/client-rpc-fops_v2.c
  xlators/protocol/client/src/client.h
Labels: release 11

#3211 Fix "unexpected operator" error resulting from using bash syntax in sh (#3174)
  xlators/mount/fuse/utils/mount.glusterfs.in
  xlators/mount/fuse/utils/mount_glusterfs.in
Labels: release 10

#3124 libglusterfs: Set errno on integer parse failure
  libglusterfs/src/common-utils.c
Labels: release 9

#3246 locks: fix fd leaks
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/common.c
  xlators/features/locks/src/posix.c
Labels: release 9

#3243 locks: fix race on client disconnect to avoid stale locks
  xlators/features/locks/src/common.c
  xlators/features/locks/src/common.h
  xlators/features/locks/src/posix.c
  xlators/features/locks/src/reservelk.c
Labels: release 10

#3244 locks: fix fd leaks
  xlators/features/locks/src/clear.c
  xlators/features/locks/src/common.c
  xlators/features/locks/src/posix.c
Labels: release 10
