Repository gluster/glusterfs, pull requests merged in 2022-01, with the labels that each got.

#3061 libglusterfs: prefer mallinfo2() to mallinfo() if available
  cli/src/cli-rpc-ops.c
  cli/src/cli-xml-output.c
  configure.ac
  libglusterfs/src/statedump.c
Labels: release 9

#3016 glusterd: Updated the log level to DEBUG for redundant logs (#2887)
  xlators/mgmt/glusterd/src/glusterd-server-quorum.c
  xlators/mgmt/glusterd/src/glusterd-utils.c
Labels: release 9

#3020 glusterd: Update custom log directory option (#2957)
  tests/cluster.rc
  xlators/mgmt/glusterd/src/glusterd.c
Labels: release 10

#3018 gluster: Removed the deprecated log commands from gluster man page
  doc/gluster.8
Labels: release 9

#2951 ec: IO failure when shrinking dispersed volume during io running (#2948)
  xlators/cluster/ec/src/ec-dir-write.c
Labels: release 10

#3015 glusterd: Added a check for available ports in the port_range
  xlators/mgmt/glusterd/src/glusterd-pmap.c
Labels: release 10

#3017 glusterd: Updated the log level to DEBUG for redundant logs (#2887)
  xlators/mgmt/glusterd/src/glusterd-server-quorum.c
  xlators/mgmt/glusterd/src/glusterd-utils.c
Labels: release 10

#3019 gluster: Removed the deprecated log commands from gluster man page (#2942)
  doc/gluster.8
Labels: release 10

#3087 dict: handle excessive log in case dict is NULL in some path (#3086)
  libglusterfs/src/dict.c
Labels: release 10

#2324 dht: fix rebalance of sparse files
  tests/bugs/distribute/issue-2317.t
  tests/volume.rc
  xlators/cluster/dht/src/dht-rebalance.c
Labels: release 9

#3101 geo-rep: AttributeError: 'list' object has no attribute 'join'
  geo-replication/syncdaemon/syncdutils.py
Labels: release 9

#3102 geo-rep: AttributeError: 'list' object has no attribute 'join'
  geo-replication/syncdaemon/syncdutils.py
Labels: release 10

#3084 leases-internal.c: fix and improve __lease_ctx_set()
  xlators/features/leases/src/leases-internal.c
Labels: release 11

#3133 glusterd: add stripe_count in volume info (#3070)
  xlators/mgmt/glusterd/src/glusterd-store.c
  xlators/mgmt/glusterd/src/glusterd-store.h
Labels: release 10

#3125 libglusterfs: Set errno on integer parse failure
  libglusterfs/src/common-utils.c
Labels: release 10

#3147 xlator.h/c: xlator struct cleanup
  libglusterfs/src/glusterfs/xlator.h
  libglusterfs/src/xlator.c
  xlators/mount/fuse/src/fuse-helpers.c
Labels: release 11

#3165 rpc/xdr: removed old version of glusterfs3
  rpc/rpc-lib/src/auth-glusterfs.c
  rpc/rpc-lib/src/rpcsvc-auth.c
  rpc/rpc-transport/socket/src/socket.c
  rpc/xdr/src/Makefile.am
  rpc/xdr/src/glusterfs3-xdr.x
  rpc/xdr/src/glusterfs3.h
  rpc/xdr/src/glusterfs4-xdr.x
  tests/line-coverage/old-protocol.t
  xlators/features/bit-rot/src/stub/bit-rot-stub-helpers.c
  xlators/features/bit-rot/src/stub/bit-rot-stub.h
  xlators/features/index/src/index.c
  xlators/features/quota/src/quota.h
  xlators/features/quota/src/quotad-aggregator.h
  xlators/features/snapview-server/src/snapview-server.c
  xlators/features/snapview-server/src/snapview-server.h
  xlators/features/upcall/src/upcall-internal.c
  xlators/features/upcall/src/upcall.c
  xlators/mgmt/glusterd/src/glusterd-utils.h
  xlators/protocol/client/src/Makefile.am
  xlators/protocol/client/src/client-common.c
  xlators/protocol/client/src/client-common.h
  xlators/protocol/client/src/client-handshake.c
  xlators/protocol/client/src/client-helpers.c
  xlators/protocol/client/src/client-rpc-fops.c
  xlators/protocol/client/src/client-rpc-fops_v2.c
  xlators/protocol/client/src/client.h
  xlators/protocol/server/src/Makefile.am
  xlators/protocol/server/src/server-common.c
  xlators/protocol/server/src/server-common.h
  xlators/protocol/server/src/server-handshake.c
  xlators/protocol/server/src/server-helpers.c
  xlators/protocol/server/src/server-helpers.h
  xlators/protocol/server/src/server-rpc-fops.c
  xlators/protocol/server/src/server-rpc-fops_v2.c
  xlators/protocol/server/src/server.c
  xlators/storage/posix/src/posix-common.c
  xlators/storage/posix/src/posix-entry-ops.c
  xlators/storage/posix/src/posix-helpers.c
  xlators/storage/posix/src/posix-inode-fd-ops.c
Labels: release 11
